version: "3.9"
services:
  pgdatabase:
    image: postgres:14.13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=netflix
    volumes:
      - "./volume/postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    expose:
      - "pgdatabase:5432"
  pgadmin:
    image: dpage/pgadmin4:8.12.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./volume/pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80"